/**
 * ESP32 / Arduino Coding Tools for NeniCoder
 *
 * Write, compile, upload, and debug microcontroller code.
 * Supports Arduino IDE CLI and ESP-IDF via command line.
 *
 * Tools:
 *   mcu_new_project    — Create a new Arduino/ESP32 project
 *   mcu_write_code     — Write .ino or .cpp source files
 *   mcu_compile        — Compile the sketch
 *   mcu_upload         — Upload to board via USB/serial
 *   mcu_serial         — Read/write serial monitor
 *   mcu_boards         — List connected boards
 *   mcu_libraries      — Search/install Arduino libraries
 *   mcu_pinout         — Get pinout info for a board
 *   mcu_example        — Generate common code examples
 *   mcu_debug          — Debug helper (common issues)
 */

import { execSync, exec } from "child_process";
import * as fs from "fs";
import * as path from "path";
import { config } from "../config.js";

// ── Helpers ───────────────────────────────────────────────

function runCmd(cmd: string, timeout = 30000): string {
  try {
    return execSync(cmd, { timeout, encoding: "utf-8", stdio: ["pipe", "pipe", "pipe"] }).trim();
  } catch (err: any) {
    return `Error: ${err.message}`;
  }
}

function runCmdAsync(cmd: string, timeout = 60000): Promise<string> {
  return new Promise((resolve) => {
    exec(cmd, { timeout, encoding: "utf-8" }, (err, stdout, stderr) => {
      if (err) resolve(`Error: ${err.message}\n${stderr}`);
      else resolve((stdout || "").trim());
    });
  });
}

function findArduinoCli(): string | null {
  const candidates = ["arduino-cli", "arduino", "C:\\Program Files\\Arduino\\arduino-cli.exe"];
  for (const c of candidates) {
    try {
      execSync(`${c} version`, { stdio: "pipe" });
      return c;
    } catch { /* not found */ }
  }
  return null;
}

function findEspIdf(): string | null {
  const candidates = ["idf.py", "C:\\Espressif\\frameworks\\esp-idf-v5.x\\tools\\idf.py"];
  for (const c of candidates) {
    try {
      execSync(`${c} --version`, { stdio: "pipe" });
      return c;
    } catch { /* not found */ }
  }
  return null;
}

// ── Project Management ────────────────────────────────────

export async function mcuNewProject(name: string, board = "esp32"): Promise<string> {
  const projectDir = path.join(config.workspace, "mcu", name);
  if (!fs.existsSync(projectDir)) {
    fs.mkdirSync(projectDir, { recursive: true });
  }

  const cli = findArduinoCli();

  if (cli) {
    // Use arduino-cli to create project
    runCmd(`${cli} sketch new "${projectDir}"`);
  }

  // Write default sketch
  const sketchFile = path.join(projectDir, `${name}.ino`);

  let template = "";
  if (board.includes("esp32")) {
    template = `/*
 * ${name} — ESP32 Project
 * Generated by NeniCoder
 */

#include <WiFi.h>
#include <WebServer.h>

// WiFi credentials
const char* ssid = "YOUR_WIFI_SSID";
const char* password = "YOUR_WIFI_PASSWORD";

// Web server on port 80
WebServer server(80);

// Built-in LED (GPIO 2 on most ESP32 boards)
const int LED_PIN = 2;

void setup() {
  Serial.begin(115200);
  pinMode(LED_PIN, OUTPUT);

  // Connect to WiFi
  WiFi.begin(ssid, password);
  Serial.print("Connecting to WiFi");
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  Serial.println();
  Serial.print("Connected! IP: ");
  Serial.println(WiFi.localIP());

  // Setup web server routes
  server.on("/", handleRoot);
  server.on("/on", handleLedOn);
  server.on("/off", handleLedOff);
  server.begin();
  Serial.println("HTTP server started");
}

void loop() {
  server.handleClient();
}

void handleRoot() {
  String html = "<html><body>";
  html += "<h1>ESP32 Control Panel</h1>";
  html += "<p><a href='/on'>Turn LED ON</a></p>";
  html += "<p><a href='/off'>Turn LED OFF</a></p>";
  html += "</body></html>";
  server.send(200, "text/html", html);
}

void handleLedOn() {
  digitalWrite(LED_PIN, HIGH);
  server.send(200, "text/plain", "LED ON");
}

void handleLedOff() {
  digitalWrite(LED_PIN, LOW);
  server.send(200, "text/plain", "LED OFF");
}
`;
  } else {
    // Generic Arduino template
    template = `/*
 * ${name} — Arduino Project
 * Generated by NeniCoder
 */

const int LED_PIN = LED_BUILTIN;

void setup() {
  Serial.begin(9600);
  pinMode(LED_PIN, OUTPUT);
  Serial.println("${name} starting...");
}

void loop() {
  digitalWrite(LED_PIN, HIGH);
  delay(1000);
  digitalWrite(LED_PIN, LOW);
  delay(1000);
  Serial.println("Blink!");
}
`;
  }

  fs.writeFileSync(sketchFile, template);

  // Write platformio.ini for PlatformIO users
  const platformIni = `[env:${board}]
platform = espressif32
board = ${board}
framework = arduino
monitor_speed = 115200
upload_speed = 921600
`;
  fs.writeFileSync(path.join(projectDir, "platformio.ini"), platformIni);

  return `Project created: ${projectDir}\nBoard: ${board}\nFiles:\n  - ${name}.ino\n  - platformio.ini`;
}

// ── Code Writing ──────────────────────────────────────────

export async function mcuWriteCode(projectName: string, filename: string, code: string): Promise<string> {
  const filePath = path.join(config.workspace, "mcu", projectName, filename);
  const dir = path.dirname(filePath);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(filePath, code);
  return `Code written: ${filePath} (${code.split("\n").length} lines)`;
}

// ── Compile ───────────────────────────────────────────────

export async function mcuCompile(projectName: string, board = "esp32:esp32:esp32"): Promise<string> {
  const projectDir = path.join(config.workspace, "mcu", projectName);
  const cli = findArduinoCli();

  if (!cli) {
    return "arduino-cli not found. Install from https://arduino.github.io/arduino-cli/\nOr use PlatformIO: pio run";
  }

  const result = await runCmdAsync(
    `${cli} compile --fqbn ${board} "${projectDir}" 2>&1`,
    120000
  );
  return result;
}

// ── Upload ────────────────────────────────────────────────

export async function mcuUpload(projectName: string, port = "auto", board = "esp32:esp32:esp32"): Promise<string> {
  const projectDir = path.join(config.workspace, "mcu", projectName);
  const cli = findArduinoCli();

  if (!cli) {
    return "arduino-cli not found. Install from https://arduino.github.io/arduino-cli/";
  }

  // Auto-detect port
  let uploadPort = port;
  if (port === "auto") {
    const ports = await runCmdAsync(`${cli} board list 2>&1`);
    const lines = ports.split("\n");
    for (const line of lines) {
      if (line.includes("Arduino") || line.includes("ESP32") || line.includes("CH340") || line.includes("CP210")) {
        const parts = line.split(/\s+/);
        uploadPort = parts[0];
        break;
      }
    }
    if (uploadPort === "auto") {
      return "No board detected. Check USB connection and drivers.\nCommon ports: COM3, COM4, /dev/ttyUSB0, /dev/ttyACM0";
    }
  }

  const result = await runCmdAsync(
    `${cli} upload --fqbn ${board} --port ${uploadPort} "${projectDir}" 2>&1`,
    120000
  );
  return result;
}

// ── Serial Monitor ────────────────────────────────────────

export async function mcuSerial(port = "auto", baud = "115200", action = "read", data?: string): Promise<string> {
  if (port === "auto") {
    // Try common ports
    const ports = ["COM3", "COM4", "COM5", "/dev/ttyUSB0", "/dev/ttyACM0", "/dev/tty.usbserial"];
    port = ports[0]; // Default to first
  }

  if (action === "read") {
    // Read from serial using Python pyserial or screen
    const result = runCmd(`python3 -c "
import serial, time
try:
    ser = serial.Serial('${port}', ${baud}, timeout=2)
    time.sleep(0.5)
    lines = []
    start = time.time()
    while time.time() - start < 3:
        if ser.in_waiting:
            line = ser.readline().decode('utf-8', errors='replace').strip()
            if line: lines.append(line)
    ser.close()
    print('\\n'.join(lines) if lines else 'No data received')
except Exception as e:
    print(f'Error: {e}')
" 2>&1`);
    return result;
  }

  if (action === "write") {
    if (!data) return "Error: data required for write";
    const result = runCmd(`python3 -c "
import serial
try:
    ser = serial.Serial('${port}', ${baud}, timeout=2)
    ser.write(b'${data.replace(/'/g, "\\'")}\\n')
    ser.close()
    print('Sent: ${data.replace(/'/g, "\\'")}')
except Exception as e:
    print(f'Error: {e}')
" 2>&1`);
    return result;
  }

  return `Unknown action: ${action}. Use: read, write`;
}

// ── Board Detection ───────────────────────────────────────

export async function mcuBoards(): Promise<string> {
  const cli = findArduinoCli();
  if (cli) {
    return runCmd(`${cli} board list 2>&1`);
  }

  // Fallback: list serial ports
  if (process.platform === "win32") {
    return runCmd(`powershell -Command "Get-PnpDevice -Class Ports | Where-Object {$_.Status -eq 'OK'} | Select-Object FriendlyName, InstanceId"`);
  }
  return runCmd(`ls /dev/tty* 2>/dev/null | grep -E "USB|ACM|usbserial"`);
}

// ── Libraries ─────────────────────────────────────────────

export async function mcuLibraries(action: string, query?: string): Promise<string> {
  const cli = findArduinoCli();
  if (!cli) return "arduino-cli not found.";

  if (action === "search") {
    if (!query) return "Error: query required";
    return runCmd(`${cli} lib search "${query}" 2>&1`);
  }
  if (action === "install") {
    if (!query) return "Error: library name required";
    return runCmd(`${cli} lib install "${query}" 2>&1`);
  }
  if (action === "list") {
    return runCmd(`${cli} lib list 2>&1`);
  }
  return `Unknown action: ${action}. Use: search, install, list`;
}

// ── Pinout Reference ──────────────────────────────────────

export async function mcuPinout(board = "esp32"): Promise<string> {
  const pinouts: Record<string, string> = {
    esp32: `
ESP32 Pinout Reference
═══════════════════════
GPIO: 0, 2, 4, 5, 12-19, 21-23, 25-27, 32-33
ADC1: GPIO 32-39 (12-bit, 0-3.3V)
ADC2: GPIO 0, 2, 4, 12-15, 25-27 (WiFi conflict!)
DAC:  GPIO 25, 26 (8-bit)
PWM:  All GPIO (ledcWrite)
I2C:  SDA=21, SCL=22 (default)
SPI:  MOSI=23, MISO=19, SCK=18, CS=5 (default)
UART: TX=1, RX=3 (default), UART1: TX=17, RX=16
Touch: GPIO 0, 2, 4, 12-15, 27, 32-33
Built-in LED: GPIO 2 (most boards)
Strapping: GPIO 0, 2, 12, 15 (avoid for general use)
Input only: GPIO 34-39 (no internal pull-up/down)
`,
    arduino_uno: `
Arduino Uno Pinout Reference
═════════════════════════════
Digital: 0-13
  PWM: 3, 5, 6, 9, 10, 11
  Serial: 0 (RX), 1 (TX)
  SPI: 10 (SS), 11 (MOSI), 12 (MISO), 13 (SCK)
  I2C: A4 (SDA), A5 (SCL)
  Interrupt: 2, 3
Analog: A0-A5 (10-bit ADC)
  A4/A5 also I2C
Power: 3.3V, 5V, GND, Vin
`,
    esp32cam: `
ESP32-CAM Pinout Reference
═══════════════════════════
Camera: D0-D7: GPIO 4, 5, 18, 19, 21, 36, 39, 34
SD Card: CLK=14, CMD=15, D0=2, D1=4, D3=13
UART: TX=1, RX=3 (programming)
Free GPIO: 0, 2, 12, 13, 15, 16
Built-in LED: GPIO 33
PSRAM: Use for camera buffer
`,
    nodemcu: `
NodeMCU ESP8266 Pinout Reference
═════════════════════════════════
Digital: D0-D8 (GPIO 16, 5, 4, 0, 2, 14, 12, 13, 15)
Analog: A0 (10-bit, 0-3.3V)
PWM: All digital pins
I2C: SDA=D2 (GPIO 4), SCL=D1 (GPIO 5)
SPI: MOSI=D7, MISO=D6, CLK=D5, CS=D8
UART: TX=GPIO1, RX=GPIO3
Built-in LED: GPIO 2 (D4) — active LOW
`,
  };

  return pinouts[board.toLowerCase()] || `Pinout for "${board}" not in database. Supported: ${Object.keys(pinouts).join(", ")}`;
}

// ── Code Examples ─────────────────────────────────────────

export async function mcuExample(type: string, board = "esp32"): Promise<string> {
  const examples: Record<string, string> = {
    blink: `// Blink LED
const int LED = ${board.includes("esp32") ? "2" : "13"};

void setup() {
  pinMode(LED, OUTPUT);
}

void loop() {
  digitalWrite(LED, HIGH);
  delay(500);
  digitalWrite(LED, LOW);
  delay(500);
}
`,
    wifi_connect: `// ESP32 WiFi Connect
#include <WiFi.h>

const char* ssid = "YOUR_SSID";
const char* password = "YOUR_PASSWORD";

void setup() {
  Serial.begin(115200);
  WiFi.begin(ssid, password);
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  Serial.println("\\nConnected!");
  Serial.println(WiFi.localIP());
}

void loop() {}
`,
    web_server: `// ESP32 Web Server
#include <WiFi.h>
#include <WebServer.h>

const char* ssid = "YOUR_SSID";
const char* password = "YOUR_PASSWORD";
WebServer server(80);

void handleRoot() {
  server.send(200, "text/html", "<h1>Hello from ESP32!</h1>");
}

void setup() {
  Serial.begin(115200);
  WiFi.begin(ssid, password);
  while (WiFi.status() != WL_CONNECTED) delay(500);
  Serial.println(WiFi.localIP());
  server.on("/", handleRoot);
  server.begin();
}

void loop() {
  server.handleClient();
}
`,
    mqtt: `// ESP32 MQTT Client
#include <WiFi.h>
#include <PubSubClient.h>

const char* ssid = "YOUR_SSID";
const char* password = "YOUR_PASSWORD";
const char* mqtt_server = "broker.hivemq.com";

WiFiClient espClient;
PubSubClient client(espClient);

void setup() {
  Serial.begin(115200);
  WiFi.begin(ssid, password);
  while (WiFi.status() != WL_CONNECTED) delay(500);
  client.setServer(mqtt_server, 1883);
  client.setCallback(callback);
}

void callback(char* topic, byte* payload, unsigned int length) {
  Serial.print("Message: ");
  for (int i = 0; i < length; i++) Serial.print((char)payload[i]);
  Serial.println();
}

void reconnect() {
  while (!client.connected()) {
    if (client.connect("ESP32Client")) {
      client.subscribe("test/topic");
    } else {
      delay(5000);
    }
  }
}

void loop() {
  if (!client.connected()) reconnect();
  client.loop();
}
`,
    sensor_dht: `// DHT22 Temperature & Humidity Sensor
#include <DHT.h>

#define DHTPIN 4
#define DHTTYPE DHT22

DHT dht(DHTPIN, DHTTYPE);

void setup() {
  Serial.begin(115200);
  dht.begin();
}

void loop() {
  float temp = dht.readTemperature();
  float hum = dht.readHumidity();

  if (isnan(temp) || isnan(hum)) {
    Serial.println("Sensor error!");
  } else {
    Serial.printf("Temp: %.1f°C  Humidity: %.1f%%\\n", temp, hum);
  }
  delay(2000);
}
`,
    oled: `// SSD1306 OLED Display (I2C)
#include <Wire.h>
#include <Adafruit_SSD1306.h>

#define SCREEN_WIDTH 128
#define SCREEN_HEIGHT 64
Adafruit_SSD1306 display(SCREEN_WIDTH, SCREEN_HEIGHT, &Wire, -1);

void setup() {
  if (!display.begin(SSD1306_SWITCHCAPVCC, 0x3C)) {
    Serial.println("SSD1306 allocation failed");
    for (;;);
  }
  display.clearDisplay();
  display.setTextSize(1);
  display.setTextColor(SSD1306_WHITE);
  display.setCursor(0, 0);
  display.println("Hello, NeniCoder!");
  display.display();
}

void loop() {}
`,
    servo: `// Servo Motor Control
#include <Servo.h>

Servo myServo;
const int SERVO_PIN = 9;

void setup() {
  myServo.attach(SERVO_PIN);
}

void loop() {
  for (int pos = 0; pos <= 180; pos += 10) {
    myServo.write(pos);
    delay(100);
  }
  for (int pos = 180; pos >= 0; pos -= 10) {
    myServo.write(pos);
    delay(100);
  }
}
`,
    bluetooth: `// ESP32 Bluetooth Serial
#include <BluetoothSerial.h>

BluetoothSerial SerialBT;

void setup() {
  Serial.begin(115200);
  SerialBT.begin("ESP32_NeniCoder");
  Serial.println("Bluetooth ready. Pair with 'ESP32_NeniCoder'");
}

void loop() {
  if (SerialBT.available()) {
    char c = SerialBT.read();
    Serial.write(c);
  }
  if (Serial.available()) {
    char c = Serial.read();
    SerialBT.write(c);
  }
}
`,
  };

  const code = examples[type.toLowerCase()];
  if (!code) {
    return `Example "${type}" not found. Available: ${Object.keys(examples).join(", ")}`;
  }
  return code;
}

// ── Debug Helper ──────────────────────────────────────────

export async function mcuDebug(issue: string): Promise<string> {
  const solutions: Record<string, string> = {
    upload_failed: `
Upload Failed — Common Fixes:
══════════════════════════════
1. Check USB cable (some cables are charge-only)
2. Install CH340/CP2102 drivers if needed
3. Hold BOOT button during upload (ESP32)
4. Try different USB port
5. Close serial monitor before uploading
6. Check port: arduino-cli board list
7. For ESP32: GPIO0 must be LOW during boot for flash mode
`,
    wifi_not_connecting: `
WiFi Not Connecting — Common Fixes:
════════════════════════════════════
1. Check SSID and password (case-sensitive)
2. Ensure 2.4GHz network (ESP32 doesn't support 5GHz)
3. Add WiFi.reconnect() in loop()
4. Check max connections on router
5. Add delay(1000) after WiFi.begin()
6. Use WiFi.setAutoReconnect(true)
7. Check if WiFi.status() == WL_CONNECTED
`,
    brownout: `
Brownout Detector Triggered:
═════════════════════════════
1. Use a better USB cable (shorter, thicker)
2. Add capacitor (100-470µF) between 5V and GND
3. Reduce WiFi transmit power: WiFi.setTxPower(WIFI_POWER_11dBm)
4. Disable brownout in menuconfig (not recommended)
5. Use external 3.3V regulator for peripherals
`,
    i2c_not_working: `
I2C Not Working — Common Fixes:
════════════════════════════════
1. Check wiring: SDA→SDA, SCL→SCL (not swapped)
2. Add 4.7kΩ pull-up resistors on SDA and SCL
3. Check address: Wire.scan() or I2C scanner sketch
4. Default ESP32 I2C: SDA=GPIO21, SCL=GPIO22
5. Some devices need 3.3V, not 5V
6. Reduce I2C speed: Wire.setClock(100000)
`,
    oled_blank: `
OLED Display Blank — Common Fixes:
═══════════════════════════════════
1. Check I2C address (usually 0x3C or 0x3D)
2. Run I2C scanner to find address
3. Check wiring: SDA, SCL, VCC, GND
4. Try: Adafruit_SSD1306 display(128, 64, &Wire, -1)
5. Some displays need reset pin
6. Check if display is 3.3V or 5V compatible
`,
  };

  return solutions[issue.toLowerCase()] || `Debug topic "${issue}" not found. Available: ${Object.keys(solutions).join(", ")}`;
}
